{"uid":"a88f9f5dc16ae461","name":"An uncaught error was detected outside of a test","fullName":".An uncaught error was detected outside of a test","historyId":"52a12849550d3513996e41b83e83be38","time":{"start":1735852417128,"stop":1735852417291,"duration":163},"description":"","descriptionHtml":"","status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n                \n                  > Invalid or unexpected token\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","statusTrace":"SyntaxError: The following error originated from your test code, not from Cypress.\n                \n                  > Invalid or unexpected token\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.\n                    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":""},{"name":"testClass","value":""},{"name":"testMethod","value":"An uncaught error was detected outside of a test"},{"name":"package","value":""},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"a88f9f5dc16ae461.json","parameterValues":[]}